### ISSUE TITLE
pages-plugin_2.11-0.8.jar does not work with Gitbucket 4.9

### ISSUE THREAD

**Issue by shiena** [yaroot/gitbucket-pages-plugin#9]
The following is the error log.

```
15:05:47.861 [main] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: /var/gitbucket/plugins/pages-plugin_2.11-0.8.jar
java.lang.AbstractMethodError: gitbucket.plugin.pages.PagesController.gitbucket$core$service$RepositoryService$_setter_$gitbucket$core$service$RepositoryService$$templateExtensions_$eq(Lscala/collection/Seq;)V
	at gitbucket.core.service.RepositoryService$class.$init$(RepositoryService.scala:426)
	at gitbucket.plugin.pages.PagesController.<init>(pages.scala:16)
	at Plugin.<init>(Plugin.scala:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at gitbucket.core.plugin.PluginRegistry$.gitbucket$core$plugin$PluginRegistry$$$anonfun$6(PluginRegistory.scala:173)
	at gitbucket.core.plugin.PluginRegistry$.gitbucket$core$plugin$PluginRegistry$$$anonfun$6$adapted(PluginRegistory.scala:170)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:170)
	at gitbucket.core.servlet.InitializeListener.gitbucket$core$servlet$InitializeListener$$$anonfun$1(InitializeListener.scala:96)
	at gitbucket.core.servlet.InitializeListener.gitbucket$core$servlet$InitializeListener$$$anonfun$1$adapted(InitializeListener.scala:37)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:37)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:837)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:810)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:411)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:378)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at JettyLauncher.main(JettyLauncher.java:91)
```

I tried to recompile with the following patch. It works fine.

```diff
diff --git a/build.sbt b/build.sbt
index 179540c..edf3e90 100644
--- a/build.sbt
+++ b/build.sbt
@@ -9,7 +9,7 @@ resolvers ++= Seq(
 )

 libraryDependencies ++= Seq(
-  "io.github.gitbucket"   %%  "gitbucket"           % "4.6.0",
+  "io.github.gitbucket"   %%  "gitbucket"           % "4.9.0",
   "javax.servlet"         %   "javax.servlet-api"   % "3.1.0"
 )
```

**Comment by yaroot** [comment]
new release on the way
